---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tenexqmh/magicdeckbuilder.click/
    - /bin/cp -R html/css $DEPLOYPATH
    - /bin/cp -R html/js $DEPLOYPATH
    - /bin/cp -R html/fonts $DEPLOYPATH
    - /bin/cp -R html/imgs $DEPLOYPATH
    - /bin/cp -R html/index.html $DEPLOYPATH
